### ISSUE TITLE
Implement Continuous Integration

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#1]
Pseudo-Story 1:
As a developer, I wish to have continuous integration set up in order to be aware of the state of the builds and test environment for my project

Priority: 2/4 (medium)
Risk: 1/5 (low)
Story Points: 2

Subtasks: #2 #12

**Comment by jacobrs** [comment]
Application is now building on [Jenkins](http://35.227.86.54/job/Signal%20Android%20Build/).

**Comment by jinfuchen** [comment]
Setup Jenkins CI environment successfully.
