### ISSUE TITLE
Swipe to Return to Conversation View

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#10]
As a user, while I am in a conversation, I want to be able to swipe to go back to the conversation list view.

Demo Steps:

- Open Signal application to conversation list view.
- Select a conversation to open.
- From this conversation, swipe right to return to the conversation list view

Sub Tasks
- #14 Locate conversation list view and conversation view activity.
- #15 Implement swiping right in the conversation view activity.
- #16 Trigger back button functionality on swipe right from conversation view activity.
- #17 Develop tests for back button triggering.

Priority: 2/4 (medium)
Risk: 2/4 (medium)
Story Points: 5

Acceptance Tests:

Testing Component | Inputs | Outputs | Status
------ | ------- | ----------- | ----
Conversation | Swipe right in a conversation | Return to conversation list | PASS
Conversation | Swipe right in an archived conversation | Return to archived conversation list | PASS
Conversation | Swipe left in a conversation | No transition to conversation list | PASS
Conversation | Swipe up or down in a conversation |  Scroll the conversation view | PASS

**Comment by jinfuchen** [comment]
Demo swiping to return to conversation view. (pass)
#14 Locate conversation list view and conversation view activity. (done)
#15 Implement swiping right in the conversation view activity. (done)
#16 Trigger back button functionality on swipe right from conversation view activity. (done)
#17 Develop tests for back button triggering. (done)
