### ISSUE TITLE
Emojii Reaction Mockups

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#104]
Make mockups for the UI for emoji reactions. Ideally, these reactions would be attached to the message they are associated with (to the message bubble, or immediately below it).

Related story; #88 
Ideal hours: 1 hour

**Comment by lori-dalkin** [comment]
- Emoji Reaction Menu Icon
![menuicon](https://user-images.githubusercontent.com/14793731/38534963-289c0304-3c4f-11e8-8e5c-f6ea0a3bdde6.JPG)

- Emoji Drawer Popup
![emojidrawerpopup](https://user-images.githubusercontent.com/14793731/38534671-48b1fc72-3c4d-11e8-884f-5325e588894c.JPG)

- Emoji Reaction Displayed
![emojireaction](https://user-images.githubusercontent.com/14793731/38534811-33ad1cde-3c4e-11e8-9155-02a840ff70b6.JPG)

**Comment by lori-dalkin** [comment]
Mockups completed.

Time spent: 1 hour
