### ISSUE TITLE
Find appropriate emojis to react with

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#105]
Find a set of appropriate emojis to use as reactions. There are already many of these in the app which can be used as a resource.

Related story: #88 
Ideal hours:  20 Minutes

**Comment by claudds** [comment]
@samantha-kerr  Searched through the assets folder. Came upon people.png in the Emoji folder. This entire page will provide sufficient reactions for our application.

Time Spent: 15 minutes

**Comment by lori-dalkin** [comment]
@samantha-kerr @claudds 
After further investigation into handling the capture of a selected emoji, it will be easier to utilize the full emoji library present in the emoji drawer of the keyboard. Therefore selecting specific emojis is no longer the case and we will handle all android native emojis.

This researched/discovery is tied to issue #107
