### ISSUE TITLE
Display emojis to add as reaction

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#107]
When the emoji reaction is chosen in the menu after long press, a list/menu of emojis that can be used as a reaction should be accessible.

Ideal hours:  5 hours
Related story: #88

**Comment by lori-dalkin** [comment]
Implemented action for when the emoji reaction icon is clicked. Utilizes the existing emoji drawer and emoji event listener to capture selected emoji. This is where we will add a handler for sending the reaction.

Time spent: 3.5 hours
