### ISSUE TITLE
Nickname A Contact

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#11]
As a user, I want to be able to rename my signal contacts in order to customize my contact list.

Demo Steps (Acceptance Criteria)
- Be able to select a contact and add a nickname.
- Contacts with nicknames should display nicknames instead of contact names.
- Nicknames should be persistent within the application
- Polling for contact information should not affect nicknames.

Sub-tasks
- #18 Make name editable on the conversation settings screen
- #19 Save nickname after the user confirms
- #20 Load nickname wherever it's needed
- #30 Write appropriate tests

Priority: 4/4 (high)
Risk: 3/4 (medium)
Story Points: 8

Acceptance Tests:

Testing Component | Inputs | Outputs | Status
------ | ------- | --------- | --------
Chat Name | Conversation with address or contact name, new chat name | Conversation with new chat name | PASS
Chat Name | Conversation with chat name, new chat name | Conversation with new chat name | PASS
Chat Name | Conversation with address or contact name, empty chat name | Conversation with address or contact name | PASS
Chat Name | Conversation with chat name, empty chat name | Conversation with address or contact name | PASS

**Comment by jacobrs** [comment]
Story is ready for Demo + Approval.

**Comment by benrs** [comment]
False, we still need tests. Will append it to the current story.

**Comment by jinfuchen** [comment]
https://docs.google.com/document/d/1Y8hvhysVrAsO73ww6PqUAF81iy6m8StQHiehzjogwAI/edit

**Comment by jinfuchen** [comment]
Demo nickname a contact. pass.
#18 Make name editable on the conversation settings screen (done)
#19 Save nickname after the user confirms (done)
#20 Load nickname wherever it's needed (done)
#30 Write appropriate tests (done)
