### ISSUE TITLE
Find and add icons for menu options

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#122]
Find appropriate icons for all existing menu options; many of these may already be in the application
Add the appropriate icons to their respective xml files.

Ideal hours: 3 hours
Related Story: #90

**Comment by lori-dalkin** [comment]
Searched through different icon sources and chose appropriate icons for the menu options in Conversation Activity with @BDSchoeler 
Added the new icons to their respective xml items.

Time Spent: 1 hour

**Comment by lori-dalkin** [comment]
Found additional icons for the Conversation List Activity and added them to their appropriate menu options.

Time Spent: 1 hour.

Task Done.
