### ISSUE TITLE
Mockups for Menu Icons

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#126]
Add mockups for new icons in the UI

Ideal hours: 1 hour
Related Story: #90

**Comment by lori-dalkin** [comment]
Attached are the mockups for this feature

- Conversation List View Menu Icons
![conversationlistmenuicons](https://user-images.githubusercontent.com/14793731/38069298-99771994-32e3-11e8-95e4-595052e013f0.JPG)

- Conversation View Menu Icons
![conversationmenuicons](https://user-images.githubusercontent.com/14793731/38069318-a311fab4-32e3-11e8-9f66-7367a5adcae9.JPG)

**Comment by lori-dalkin** [comment]
Added mockups to main issue as well.
Time Spent: 1 hour
