### ISSUE TITLE
Locate Conversation List view and Conversation view Activities

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#14]
In the code base, locate where the conversation list view and conversation view activities are, and how they connect to each other

Ideal hours: 2.5 hours

- [x] Claudia
- [x] Sam

Related stories: #10

**Comment by claudds** [comment]
Researched the ConversationListActivity and the ConversationActivity. We would need to start at the ConversationActivity and possibly trigger the onBackPressed() function to return to the conversation list (or implement a similar function when a swipe is detected).

Looking at other examples for swiping implementation, I found the swiping implementation for archiving in ConversationListFragment (459-575). This can be a good starting point to understand how swiping is detected and reacted to. 

Default animation for returning to the Conversation List view is an animation of the screen pulling off to the right. We could use this for our intended purposes as well.

Time spent: 2 hours

**Comment by samantha-kerr** [comment]
@claudds I looked into ConversationListActivity and ConversationActivity as you mentioned. From what I see in the archiving example, ItemTouchHelper might be the class to look into to set up the transition for swiping back. There is the handleReturnToConversationList() event handler in ConversationActivity (579-584) that we need to consider as well.

Time spent: 1 hour
