### ISSUE TITLE
Android unit tests do not have permission to write to storage.

### ISSUE THREAD

**Issue by BDSchoeler** [jacobrs/Signal-Android#145]
Determine why android unit tests do not have proper permissions, and find a way to fix this issue.

**Comment by benrs** [comment]
After looking into it the problem has to do with the fact that android systems are built to be read-only, if we wanted to fix this we'd either have to run the tests with a root configuration or remount the system to be in read-write mode. I'm not sure if that is easy in our scenario so I'll close this as won't do, if anyone has other input then feel free to add it here.
