### ISSUE TITLE
Implement Swiping Right in Conversation View Activity

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#15]
In the conversation view activity, implement a feature that allows the user to swipe right across the screen with their finger.  Integrate a swiping animation to go along with this feature.

Ideal Hours: 10 hours
Related Stories: #10

**Comment by claudds** [comment]
Tried implementing swiping functionality. Manual tests were inconclusive; GestureDetector listeners were unable to catch swiping gestures in the emulator.
3.5 hrs

**Comment by samantha-kerr** [comment]
Also tried implementing the swiping functionality using the GestureDetector class, without success. Need to do more investigation into this strategy.
Time: 2.5 hrs

**Comment by claudds** [comment]
@samantha-kerr Pair programming: Tried implementing swiping feature using Gesture Detector in the ConversationFragment and ConversationActivity class. Learned that scrolling features are catching the swiping gestures with the onScrollListener. Must find a way around this.

Time spent: 2.5 hrs

**Comment by claudds** [comment]
@samantha-kerr 

Last night: implemented gesture detection in the ConversationFragment with ScrollListener. However, due to horizontal scrolling being disabled, this was not a viable option. Then attempted to implement swiping similar to the way it was done for archiving, by attaching a listener to the list view. This resulted in messages being swiped but not the screen. Spent 2.5 hours

Today: Implemented gesture detection again in the Conversation activity and found a way to intercept touch events and dispatch them to the appropriate listeners (so that scrolling was not blocking out swiping). Implemented swipe functionality successfully. Spent 3 hours
