### ISSUE TITLE
Trigger Back Button Functionality

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#16]
Upon swiping right in the conversation view activity, trigger the back button functionality to take the user back to the conversation list view. 

Ideal Hours: 5 hours
Related Stories: #10

**Comment by samantha-kerr** [comment]
@claudds 
Implemented the back button functionality when swiping right on the conversation view activity by simply triggering the handleReturnToConversationList event. Manually tested to make sure that swiping right will bring you back either to conversation list view when the conversation is not archived, and to the archived list if the conversation is archived. Using the same simple transition animation to go back to conversation list as when clicking the back button; it seems appropriate considering the swipe we catch is a fling. 
Time Spend: 30min
