### ISSUE TITLE
Locate conversation view activity (1.5 hr)

### ISSUE THREAD

**Issue by BDSchoeler** [jacobrs/Signal-Android#21]
In the code base, locate where the conversation list view, and see how a conversation can be archived.

Ideal hours: 1.5 hours

- [x] Bryce
- [x] Lori

Related stories: #9

**Comment by lori-dalkin** [comment]
With @BDSchoeler 

Located conversation view activity within ConversationListFragment.
Will use the ArchiveListenerCallback class to create a DeleteListenerCallback that would call the already existing delete message functionalities.
