### ISSUE TITLE
Implement swiping left on a conversation node 

### ISSUE THREAD

**Issue by BDSchoeler** [jacobrs/Signal-Android#22]
Implement the ability to swipe left on a conversation node in the conversation list view. The animation should be similar to that of archive but with a different icon.

Ideal hours: 7 hours

Related stories: #9

**Comment by lori-dalkin** [comment]
Note: Animation will possibly be pushed to next sprint.

(Edit) Based on how fast this task was completed, animation is still left to be considered. Will create new subtask for animation that will continue off of the remaining estimated time from this subtask.

**Comment by lori-dalkin** [comment]
@BDSchoeler 

Created a DeleteListenerCallback class (based on the ArchiveListenerCallback). Hooked up the class with the ItemTouchHelper to keep track of guestures. 
Manual tests on the emulated android device shows that swiping left archives a conversation as well now. 
After the previous subtask research (#21 ), this subtask was faster than expected. Fixing the emulator, other miscellaneous android studio errors and build times increased the overall work time.
Time spent: 3 hours

**Comment by lori-dalkin** [comment]
Commit message referenced the wrong story. #9 is the correct story.
