### ISSUE TITLE
Change the display message when deleting a conversation.

### ISSUE THREAD

**Issue by BDSchoeler** [jacobrs/Signal-Android#29]
Change the display message from "archived conversation" to "deleted conversation" when deleting conversation.

Ideal Hours: 2 hours
Related Stories: #9

**Comment by lori-dalkin** [comment]
@BDSchoeler 

Found resources for user facing string relating to deletion. Replaced archive specific messages/functionality with delete.
Time Spent: 2 hours

**Comment by lori-dalkin** [comment]
@BDSchoeler 

Note: We may wish to alter our design flow for deletion. Currently when manually deleting from either ConversationListView or ArchiveListView, a pop up warning appears to ensure the user wishes to delete their conversation. While adding this to swipe to delete might lessen the ease of swiping to delete, this protocol may be desired.
