### ISSUE TITLE
Extract Project Architecture

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#3]
As a software developer, I would like to have an overview of Signal's software architecture in order to implement new features in the proper place and enhance this architecture.

Priority: 4/4 (High)
Risk: 3/4 (medium)
Story Points: 5

Subtasks: #4 #5

**Comment by jinfuchen** [comment]
Extract component diagram.(Done)
Extract activity architecture.(Done)
You can create the mockups of the whole project by using the screenshot. Mockups can help you know the flow the UI. It is helpful for the implementation of the basic feature.
