### ISSUE TITLE
Mark Message as Unread

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#36]
As a user, I wish to have the option to mark a message as unread in order to bring back the notification so that I may have a reminder to re-read this message at a later time.

NOTE: This will have no effect on the recipient's view of the message's read status.

Priority: 2/4
Risk: 2/4
Story Points: 3

# Demo steps (acceptance criteria):
1. Open the Signal Application and access a conversation with an unread message
2. Note that the message notification has been cleared.
3. Long press a message
4. In the resulting toolbar, choose to mark a message as unread
5. Note that the unread message notification will again appear

# Subtasks
#51 UI Mockup for marking a message as unread
#52 Implement the change to the Read field 
#53 Add menu option to mark a message as unread
#54 Test marking as unread
#55 Document marking as unread
#70 Mark messages as unread look different
#71 Allow user to unmark as unread

# Acceptance Tests
Testing Component | Inputs | Outputs | Status
------ | ------- | --------- | --------
|mark as unread |long press on Conversation Item | Mark as unread icon appears in  menu | PASS
|mark as unread | long press on conversation item, tap mark as unread icon | message marked as unread, conversation activity closes | PASS
|mark as unread| long press multiple messags, tap Mark as Unread icon | messages are marked as unread, activity closes| PASS
| mark as unread | long press on message already marked as unread | Mark as unread does not appear in menu | PASS
| mark as unread | long press on multiple messages, some already marked as unread | mark as unread icon does not appear in menu | PASS
| mark as unread | mark message as unread | conversation activity closes and returns to conversation list view | PASS
| mark as unread | mark message as unread | conversation in conversation list shows unread messages | PASS
| mark as unread | mark message as unread, then reopen the conversation | Conversation no longer show unread messages | PASS
|mark as unread | mark message as unread, then reopen conversation | messages that were marked as unread are marked with blue exclamation mark | PASS
| mark as unread | tap a message marked as unread | blue exclamation point disappears | PASS

![markasunread](https://user-images.githubusercontent.com/15068038/36886622-50a020fe-1dbb-11e8-918f-4b02fdb45d68.png)
![markasunread2ss](https://user-images.githubusercontent.com/15068038/36886637-5e1bdd04-1dbb-11e8-977f-8af3bc05cc75.PNG)
<img width="251" alt="markasunread4" src="https://user-images.githubusercontent.com/15068038/36886880-7b2e65f0-1dbc-11e8-9314-b81338ad7017.PNG">

**Comment by jinfuchen** [comment]
Feature as mark messages as unread is done. 
Added Demo steps (acceptance criteria) into story description, which is good.
Unit test is good.
Please add your UI test as soon as possible for this feature.
For the code
(1)In class ConversationFragment.java, 695 line, after you return statement, the function should return. Why you still add case statement?
(2)In class MmsDatabase.java, 465 line, there is no catch block following the try block?

**Comment by claudds** [comment]
1) For the ConversationFragment.java, the method in question is a switch statement, which is checking which action button in the menu was pressed; thus, a new case was added after the already existing cases. Each existing case contains its own return statement in order to avoid entering any other cases (each case in the switch statement corresponds to one menu button)

2) this issue was caught by @lori-dalkin & @jacobrs, as they also made changes to these files. Lori is dealing with fixing these missing catch statements in the database files currently.
