### ISSUE TITLE
Pin Messages

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#38]
As a user, I wish to have the ability to pin messages in a conversation to the bottom of the conversation in order to more easily access these messages.

Priority: 3/4
Risk: 3/4
Story Points: 5

# Demo Steps (acceptance criteria):
1. Open the Signal Application and access a conversation
2. Long Press a single message. A toolbar will appear at the top of the screen
3. Choose to pin the message
4. Click on settings (three dots) and select "View Pinned" to go to Pinned Messages Activity View.

# Subtasks:
#45 Pinned Message UI Mockup @lori-dalkin 
#41 Pinned Message Elements in Conversation View Activity @lori-dalkin 
#42 Load all pinned messages within new Pinned Messages activity @jacobrs 
#43 Testing pinned messages @lori-dalkin & @jacobrs 
#44 Documenting Pinned Messages feature @lori-dalkin & @jacobrs 

# Acceptance Tests
Testing Component | Inputs | Outputs | Status
------ | ------- | --------- | --------
| Pin message | Long press on message | Pin icon appears in menu | PASS 
| Pin message | Long press on message, click pin icon | Small pin icon appears on selected message | PASS
| Pin message | Long press on multiple messages | No pin icon appears in menu | PASS
| Unpin message | Long press on message | Unpin icon appears in menu | PASS 
| Unpin message | Long press on a pinned message, click unpin icon | Small pin icon disappears on selected message | PASS
| Unpin message | Long press on multiple messages | No pin icon appears in menu | PASS
| View pinned messages | Press three dot icon | "View pinned messages" action appears in drop down | PASS
| View pinned messages | Press three dot icon, press "View pinned messages" | Pinned messages activity opens, displays all pinned messages | PASS
| View pinned messages | Recipient with no profile name | Recipient's address | PASS

#  Final Design

- Pin and Unpin Icons
![image](https://user-images.githubusercontent.com/14793731/36942918-3f444c52-1f4d-11e8-86c6-f5cc23f1608a.png)
![image](https://user-images.githubusercontent.com/14793731/36942920-49c4703a-1f4d-11e8-8431-6171524613df.png)
- Small pin icon for messages
![image](https://user-images.githubusercontent.com/14793731/36942893-6888b20c-1f4c-11e8-971b-46fd22cef188.png)
- Accessing Pinned Messages Activity
![image](https://user-images.githubusercontent.com/14793731/36942896-97d6a2da-1f4c-11e8-834a-ffe198a3eb61.png)
![image](https://user-images.githubusercontent.com/14793731/36942912-2c091d20-1f4d-11e8-9aea-85abc396ed38.png)

**Comment by jinfuchen** [comment]
Feature of pin massages is done. And enough code and work.
Story points, risk, priority is good. Added Demo steps (acceptance criteria) into story description is good. Task breakdown is good. 
Mockups and acceptance tests are all good.
Please add UI tests for this feature.
For the code quality, some try blocks miss catch block.
