### ISSUE TITLE
Search Through Conversation

### ISSUE THREAD

**Issue by samantha-kerr** [jacobrs/Signal-Android#40]
As a user, I wish to have the ability to search for text within a conversation in order to more easily find a particular message.

Priority: 4/4
Risk: 3/4
Story Points: 8

# Demo Steps (acceptance criteria):
1. Open the Signal application and access an existing conversation
2. Select the option to search from the conversation menu
3. Enter a search term
4. Check the resulting messages containing your search term

# Subtasks
#59 Searching UI Mockup @samantha-kerr @claudds 
#60 Search box and Icon @claudds 
#61 Apply search term to messages @jacobrs 
#62 UI for highlighting searched terms @samantha-kerr 
#63 Tests for searching @samantha-kerr @jacobrs @claudds 
#64 Documentation for searching @samantha-kerr @claudds 

# Acceptance Tests
Testing Component | Inputs | Outputs | Status
------ | ------- | --------- | --------
SearchView text changes | any text that is not empty | should refresh list with filter applied | PASS
SearchView text reverts to empty | empty string | should cancel the search filter | PASS
SearchView back press | when pressed | should cancel the search filter | PASS
SearchView icon | when pressed | should popup the keyboard and focus on textedit | PASS
Filtered conversation | when term inserted | should highlight term in messages | PASS
Highlight colour | when shown | should be visible (not blend in) | PASS
Search filtering | when search term not empty | should filter with case insensitive term | PASS
Search Highlighting | when search term not empty | should highlight with case insensitive term | PASS

# Mockups
![searchconversation1](https://user-images.githubusercontent.com/15068038/37183481-47ded08e-2304-11e8-85bc-c8e7739b07ad.png)

![searchbarmockup](https://user-images.githubusercontent.com/14853611/37189774-fc5e5ff6-2323-11e8-84b8-2c39bb62c0ab.png)

![highlightedsearchtext](https://user-images.githubusercontent.com/14853611/37224230-da214714-23a0-11e8-9107-b34fddad9d65.png)

**Comment by jinfuchen** [comment]
Feature of searching through conversation is done.
Story description is good.
Story points, risk, and priority are all good.
Task breakdown is good. Assignee is good.
Mockup is good.
Acceptance tests are all good.
