### ISSUE TITLE
Pinned Message Elements in Conversation View Activity

### ISSUE THREAD

**Issue by jacobrs** [jacobrs/Signal-Android#41]
Add menu icon for pinning a message. 
Implement logic that will mark messages as pinned in the local database on icon click.
Add pinned indicator icon for individual pinned messages.

Ideal Hours: 5 hours
Related Story: #38

**Comment by lori-dalkin** [comment]
As the three commit messages indicate, I added a new menu action after long pressing a message to pin a message. This toggles a pinned attribute within the Sms and Mms Databases (depends on the type of message) via an on click listener that calls its specific handler. Now when a message is pinned, a small pin icon appears within the message box.

Changed how unpin and pin are handled. Now they are both separate icons that appear depending on the current pin status of the message. 

Time spent: 5 hours
