### ISSUE TITLE
Testing Pinned Messages

### ISSUE THREAD

**Issue by jacobrs** [jacobrs/Signal-Android#43]
Implement UI, Acceptance and Unit tests for story #38 and all related subtasks to ensure quality of the deliverable.

Ideal Hours: 5 hours
Related Story: #38

**Comment by lori-dalkin** [comment]
Added tests for Issue #41. 
Tests verify that the correct db methods are called from the ConversationFragment and tests that pinning puts the correct value in the db when using newly implemented methods.

Time Spent: 2 hours.
