### ISSUE TITLE
Pinned Messages UI Mockup

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#45]
Take screenshots of the existing UI, and add to these screenshots specifics for pinning messages to a conversation

Ideal Hours: 2 hours
Related Story: #38

**Comment by lori-dalkin** [comment]
Mockups created. 
1.  Long-press menu mockup, added pin icon [Here](https://drive.google.com/file/d/1Lswje5m4EyAKWvfHlK8wIhQn_UikguHO/view?usp=sharing)

2. Pinned message activity view [Here](https://drive.google.com/file/d/1SmVkZ23ZhcdMYFQyd_1HLR261hT4ddiL/view?usp=sharing)

3. Unpin message, long-press menu mockup, added pin icon [Here](https://drive.google.com/file/d/1pvUfbJsUDE-myPabHReFDWz0gGTKMQG0/view?usp=sharing)

Time spent: 1.5hours
