### ISSUE TITLE
Research Video Compression Libraries

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#46]
Conduct research into compression libraries that would allow the compression of video files being sent

Ideal Hours: 2 hours
Related Stories: #34

**Comment by samantha-kerr** [comment]
Researched video compression libraries for Android and found SiliCompressor ([https://github.com/Tourenathan-G5organisation/SiliCompressor](uri)) a library that will allow us to compress video files when shared. 

Also conducted a quick search of the codebase to determine how image files are compressed, to determine a base for implementing video compression. As it stands, the files MediaConstraints (70-87), MediaStream, and MmsMediaConstraints in the mms folder, and SendJob (52-77) in the job folder are classes of interest in terms of resizing images when sending an MMS message. Will investigate further. 

Time Spend: 1.5 hours

**Comment by BDSchoeler** [comment]
Looked into how Signal sends attachments. The attachment class works with file path and class name, which means that the methods that sillicompressor library provides should be sufficient and can be integrated to SendJob class to compress videos if the video size is too large.
