### ISSUE TITLE
Test Video Compression 

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#49]
Implement Tests (Unit tests, acceptance tests) for video compression feature

- [x] Unit Test
- [x] Acceptance Test

Ideal Hours: 6 hours
Related Stories: #34

**Comment by BDSchoeler** [comment]
The compression library fails to get meta data from the image when ran in the test. So unit tests that rely on the library are impossible to run.  A native function is not correctly imported/ran, so when the method is called it always returns null. This problem can not be fixed without modifying the library code. So we will test if it throws correct exceptions only.
