### ISSUE TITLE
Fix Existing Espresso Tests that are failing

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#57]
Within the AndroidTest directory, there are currently existing test which are failing due to unknown reasons. These must be fixed in order to run espresso tests for the application.

Ideal Hours: 2h
Related Story: #56

**Comment by benrs** [comment]
There was a problem with the gradle file which was causing the build under androidTest to fail. Investigated and fixed. Also a correction to this issue: there were no preexisting espresso tests, they are just more involved unit tests, closer to integration tests. On another note fixing the gradle build problems makes it so we can create espresso tests. Hours Spent: 2.5h.
