### ISSUE TITLE
Searching UI Mockup

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#59]
Using the existing application, add new UI features to screenshots for searching through a conversation.

Ideal Hours:  1
Related Story: #40 

![searchconversation1](https://user-images.githubusercontent.com/15068038/37183491-510c68ba-2304-11e8-8cf9-67488aed5802.png)

![searchbarmockup](https://user-images.githubusercontent.com/14853611/37189774-fc5e5ff6-2323-11e8-84b8-2c39bb62c0ab.png)

![highlightedsearchtext](https://user-images.githubusercontent.com/14853611/37224230-da214714-23a0-11e8-9107-b34fddad9d65.png)

**Comment by claudds** [comment]
Added mockup for menu option to search through a conversation.

![searchconversation1](https://user-images.githubusercontent.com/15068038/37166396-ebea5a32-22cc-11e8-82fb-d7f2bf41836c.png)

Time spent: 25 minutes

**Comment by claudds** [comment]
Replaced previous menu  mockup with a magnifying glass mockup for a more user friendly and easy to find search design. 

(see subtask description for mockup)
time spent: 15 minutes

**Comment by samantha-kerr** [comment]
Added mockup for search bar appearance after clicking the magnifying glass icon.
The search bar design is the same as the one seen on the conversation list view, as well as the green magnifying glass icon on the keyboard which will perform the search when pressed. 

![searchbarmockup](https://user-images.githubusercontent.com/14853611/37189811-41f9c9c4-2324-11e8-8c67-2a19636a3510.png)

Time spent: 15 minutes

**Comment by samantha-kerr** [comment]
Added mockup for search results after performing the search. Only messages containing the searched word will appear on the screen. The searched keyword is highlighted in each message. 

![highlightedsearchtext](https://user-images.githubusercontent.com/14853611/37224213-cc0e5bbc-23a0-11e8-86c0-d83625a4b01e.png)

Time Spent: 45 minutes
