### ISSUE TITLE
Tests for Searching through a conversation

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#63]
Implement unit and acceptance tests for searching through a conversation

- [x] unit tests
- [x] acceptance tests
- [x] espresso tests

Ideal hours: 6hrs
Related Story: #40

**Comment by claudds** [comment]
Wrote basic unit tests for testing the highlighting, binding, and retrieval of cursors. Nothing passes currently, due to various null pointer exceptions, even though all things are adequately mocked in the same way that they are mocked in current, passing unit tests using those same elements. Will look further into this tomorrow

Time spent: 5.5 hours

**Comment by samantha-kerr** [comment]
Wrote a basic UI Espresso test for searching in a conversation. Test shows the display of messages in the conversation body before searching and the resulting messages displayed after a search is performed. Only messages containing the searched term are displayed in the conversation body. Had some trouble with setting up the Espresso test, but was able to run the test correctly after #98 test fixes. 

Time Spent: 5 Hours

**Comment by claudds** [comment]
Yesterday, fixed up the conversation item unit test issues, allowing all test cases to pass. Added test cases for failing search terms, and cases where case insensitivity should happen. 

Time spent: 4 hours
