### ISSUE TITLE
Fingerprint Authentication UI Mockup

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#65]
Design a UI which asks for the fingerprint authentication given that the user has this option set.
Using the current menu UI, design a mockup UI for the menu option to set fingerprint aut

Ideal Hours: 1 hr
Related story: #37

**Comment by lori-dalkin** [comment]
Attached are the mockups for this feature

- Settings Disabled
![settingsdisabled](https://user-images.githubusercontent.com/14793731/37177183-b75d0c9a-22ec-11e8-93a0-0a200bf891ea.JPG)

- Settings Enabled
![settingsenabled](https://user-images.githubusercontent.com/14793731/37177202-bee09fb8-22ec-11e8-8d78-5ca9405cc908.JPG)

- Fingerprint Authorization Homescreen
![fingerprint authorization](https://user-images.githubusercontent.com/14793731/37177221-ca1085f6-22ec-11e8-9ea1-b98d169944b7.JPG)

**Comment by lori-dalkin** [comment]
Added mockups to main issue as well.
Time Spent: 1hr
