### ISSUE TITLE
Import fingerprint api and implement backend logic

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#66]
Import the Android api that allows fingerprint authentication. Note, this should be using the phone's native fingerprint functionality and should not store a new fingerprint specific to the app.

Ideal Hours: 10 hr
Related Story: #37

**Comment by BDSchoeler** [comment]
Task is completed, whenever the password is changed, a new keypair is created and the password is encrypt. The password can only be decrypted when the user identifies themselves with their finger print. Total time spent over 10 hours.

**Comment by lori-dalkin** [comment]
Incorporated some of the logic from my subtask into this subtask to deal with the toggling of the fingerprint authentication enabling.
