### ISSUE TITLE
Research Contact Storage

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#8]
As a software developer, I want to research whether or not the application imports and stores contact information in order to prepare for the next sprint's development.

Priority: 2/4 (medium)
Risk: 1/4 (low)
Story points: 1

**Comment by claudds** [comment]
It seems as though the contacts are stored by the app (there's a class in the contacts module called ContactsDatabase). The app also polls the user's contacts and syncs app contact's with the user's contacts (ContactSyncAdapter).

**Comment by jinfuchen** [comment]
Prepare for the basic feature. (Done)
