### ISSUE TITLE
Swipe to Delete Conversation

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#9]
As a user, I want to be able to swipe across the screen to delete a conversation from history.

Demo Steps (Acceptance Criteria)
- Open Signal application to conversation list view.
- Swipe left on desired conversation to delete.
- Conversation should no longer appear in the conversation list view nor the archived conversation list view.

Sub Tasks
#21 Locate conversation view activity (1.5 hr)
#22 Implement swiping left on a conversation node (7 hrs)
#23 Connect delete function with swiping. (3 hrs)
#24  Develop tests for delete functionality  (3 hrs)
#28 Animate swipe left action*
#29 Change the display message when deleting*

*Branched off subtasks from #22 

Acceptance Tests:

Testing Component | Inputs | Outputs | Status
------ | ------- | ----------- | ----
Conversation | Swipe left on conversation | Conversation deleted  | PASS
Conversation | Swipe left on an archived conversation | Conversation deleted | PASS
Conversation | Swipe right on a conversation | Conversation archived | PASS
Conversation |  Swipe left on an archived conversation |  Conversation un-archived | PASS

Priority: 3/4 (medium)
Risk: 2/4 (medium)
Story Points: 5

**Comment by jinfuchen** [comment]
Demo swiping to delete conversation. (pass)
#21 Locate conversation view activity (done)
#22 Implement swiping left on a conversation node (done)
#23 Connect delete function with swiping. (done)
#24 Develop tests for delete functionality (done)
#28 Animate swipe left action (done)
#29 Change the display message when deleting (done)
