### ISSUE TITLE
Icons beside menu options

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#90]
As a user, I would like to see icons beside menu options in Signal, in order to more quickly and easily identify the functionality I am looking for.

Priority: 2/4
Risk: 1/4
Story Points: 3 

# Demo Steps (acceptance criteria)

# Subtasks
#126 Mockups @lori-dalkin
#122 Find and add icons for menu options @lori-dalkin
#123 Add icons to menu UI @lori-dalkin @BDSchoeler 
#124 Tests for menu icons @BDSchoeler 
#125 Document menu icons @lori-dalkin

# Acceptance Tests
Testing Component | Inputs | Outputs | Status
------ | ------- | --------- | --------
Icons visible conversation list view  | View overflow actions on conversation list view | All options have an icon | PASS
Icons visible conversation view  | View overflow actions on conversation view  | All options have an icon | PASS

# Mockups

- Conversation List View Menu Icons
![conversationlistmenuicons](https://user-images.githubusercontent.com/14793731/38069391-0f335404-32e4-11e8-8ffc-9bc461da247c.JPG)

- Conversation View Menu Icons
![conversationmenuicons](https://user-images.githubusercontent.com/14793731/38069403-16798800-32e4-11e8-8a13-e1d0dbc15599.JPG)

**Comment by lori-dalkin** [comment]
Added @BDSchoeler as new additional assignee for this story.
