### ISSUE TITLE
Error Tolerance for Swipe to Delete

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#91]
As a user, I would like to see an option to undo an accidental delete when swiping right on a conversation, in order to safeguard against accidental deletions.

Priority: 3/4
Risk: 3/4
Story Points: 3 

# Demo Steps (acceptance criteria)

# Subtasks
#127 Implement design pattern
#128 Trigger design pattern
#129 Testing
#130 Documentation for feature

# Acceptance Tests
Testing Component | Inputs | Outputs | Status
------ | ------- | --------- | --------
Swiping to delete | on conversation | should show snackbar | PASSED
Snackbar message | when deleting | should show "Deleted Conversation" | PASSED
Snackbar action | when deleting | should show "UNDO" | PASSED
Snackbar action | when deleting | should be pink | PASSED
Snackbar action | when selected | should bring the conversation back | PASSED
Snackbar action | when not selected | should perform deletion  | PASSED

# Mocks
<img width="395" alt="screen shot 2018-03-31 at 2 12 01 pm" src="https://user-images.githubusercontent.com/6232934/38166195-bd77dd54-34ed-11e8-80e0-6474dc3910e1.png">

**Comment by jinfuchen** [comment]
Please add assignee to the sub-task.
