### ISSUE TITLE
Research Translation APIs

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#94]
Do some research for possible translation APIs which are free and allow unlimited calls to the service.

Ideal Hours:
Related story: #93

**Comment by benrs** [comment]
After researching for about 1 hour and reading into the APIs our best choice is to either go with Yandex https://tech.yandex.com/translate/doc/dg/reference/translate-docpage/ pricing: https://translate.yandex.com/developers/offer/prices + free option: https://translate.yandex.com/developers/offer, or microsoft's translation API https://azure.microsoft.com/en-us/pricing/details/cognitive-services/translator-text-api/. Leaning more towards Yandex.
