### ISSUE TITLE
Double Tap to flip camera

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#95]
As a user, I wish to be able to double tap to change camera direction when I am direct capturing a video/photo to send as an attachment, in order to more easily handle the camera and more quickly send an attachment.

Priority: 4/4
Risk: 2/4
Story Points: 5

# Demo Steps (acceptance criteria)
1. Open Signal Application
2. Open a conversation and select to attach an attachment
3. Select the "camera" option
4. The camera will open. Double tap on the camera, flipping the view

# Subtasks
#131 Find direct capture activity @claudds 
#132 Set up on touch listener @samantha-kerr @claudds 
#133 Implement double tap @samantha-kerr @claudds 
#134 Test double taps
#135 document double taps

# Mockups
![preview-back-facing](https://user-images.githubusercontent.com/15068038/38165589-c5b49e8a-34e3-11e8-9306-b637abaf73ca.png)
![preview-front-facing](https://user-images.githubusercontent.com/15068038/38165592-c898bab4-34e3-11e8-8efe-c8307a60407d.png)
![full-screen-back-facing](https://user-images.githubusercontent.com/15068038/38165593-ce5d0b6c-34e3-11e8-971c-ff752e857915.png)
![full-screen-front-facing](https://user-images.githubusercontent.com/15068038/38165594-d204630a-34e3-11e8-96a2-0375026fc81e.png)

# Acceptance Tests
Testing Component | Inputs | Outputs | Status
------ | ------- | --------- | --------
| Quick Attachment Drawer preview| Double tap on front-facing camera  |  Camera direction flips to back facing, icon changes to back facing icon  | PASS
| Quick Attachment Drawer preview | Double tap on back facing camera |  Camera direction flips to front-facing, icon changes to front facing icon | PASS
| Quick Attachment Full Screen | Double tap on front-facing camera | Camera direction flips to back facing, icon changes to back facing icon | PASS
| Quick Attachment Drawer full screen | Double tap on back facing camera | Camera direction flips to front facing, icon changes to front facing icon | PASS
|Quick Attachment drawer preview | Single tap on camera | camera does not change direction, icon remains the same | PASS
| Quick Attachment Drawer full screen | Single tap on camera | camera does not change direction, icon remains the same | PASS

**Comment by jinfuchen** [comment]
Please add assignee to the last two sub-tasks.
