### ISSUE TITLE
Image Compression

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#96]
As a user, I wish for my images to be compressed when sending an attachment, in order to more efficiently send photos using less data.

Priority: 2/4
Risk: 1/4
Story Points: 3

# Demo Steps (acceptance criteria)

# Subtasks
#136 Compress images
#137 Test image compression
#138 Document image compressiom

# Acceptance Tests
Testing Component | Inputs | Outputs | Status
------ | ------- | --------- | --------
| |  |

**Comment by BDSchoeler** [comment]
Already implemented so nothing to do here. I thought they were only resizing the image, because the methods names were resizebitmap, and isResizeable, but it turns out they are doing proper image compression.
